- hosts: Amazon
  gather_facts: true
  remote_user: ec2-user
  become: yes
  vars:
    rbenv:
      env: user
      default_ruby: 2.5.5
      rubies:
      - version: 2.5.5
  roles:
    - epel
    - rbenv
    - gem
    - nodejs
    - ocha.yarn
    - nginx
